name: delete_py

on:
   workflow_dispatch:

job:
  build:
    runs-on:ubuntu-latest
    
    steps:
      - id: remove
          name: Remove File
          uses: JesseTG/rm@v1.0.3
          with:
          path: ./archivo_ejemplo_01.py

 # Add new files in folder, commit along with other modified files, push
      - id: commit
        name: Commit files
        run:
          git config --local user.name actions-user

          git config --local user.email "actions@github.com"

          git add *

          git commit -am "GH ACTION Headlines $(date)"

          git push origin main

        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}

          username: github-actions