name: delete_py

on:
  
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 

    - id: commit
      name: Commit files
      run:
        git config --global user.name actions-user
        #git rm archivo_ejemplo_01.py
        #git commit -m "remove archivo_ejemplo_01.py"
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}

        username: github-actions