name: delete_py

on:
  
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: rm ./archivo_ejemplo_01.py

 # Add new files in folder, commit along with other modified files, push
      - id: commit
        name: Commit files
        run:
          git config --local user.name actions-user

          git config --local user.email "actions@github.com"

          git add *

          git commit -am "GH ACTION Headlines $(date)"

          git push origin main

        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}

          username: github-actions