name: delete_py

on:
  
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
        - run: | 
                find archivo_ejemplo_01.py

    - id: commit
      name: Commit files
      run:
        git rm archivo_ejemplo_01.py
        git commit -m "remove archivo_ejemplo_01.py"

      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}

        username: github-actions